-- Durable queue: every user mutation and its delivery intent commit together.
CREATE TABLE native_sync_control (singleton INTEGER PRIMARY KEY CHECK(singleton=1), cursor TEXT NOT NULL DEFAULT '0', applying INTEGER NOT NULL DEFAULT 0 CHECK(applying IN (0,1)), last_success TEXT);
INSERT INTO native_sync_control(singleton) VALUES(1);
CREATE TABLE native_sync_meta(entity_table TEXT NOT NULL, id TEXT NOT NULL, revision TEXT, remote_updated_at TEXT, PRIMARY KEY(entity_table,id));
CREATE TABLE native_sync_outbox(seq INTEGER PRIMARY KEY AUTOINCREMENT, operation_id TEXT NOT NULL UNIQUE DEFAULT(lower(printf('%s-%s-%s-%s-%s',hex(randomblob(4)),hex(randomblob(2)),hex(randomblob(2)),hex(randomblob(2)),hex(randomblob(6))))), entity_table TEXT NOT NULL, id TEXT NOT NULL, action TEXT NOT NULL CHECK(action IN ('put','delete')), payload TEXT, base_revision TEXT, base_updated_at TEXT);
CREATE INDEX native_sync_outbox_entity ON native_sync_outbox(entity_table,id,seq);
CREATE TABLE native_sync_conflicts(entity_table TEXT NOT NULL, id TEXT NOT NULL, remote TEXT NOT NULL, PRIMARY KEY(entity_table,id));
INSERT INTO native_sync_meta(entity_table,id,remote_updated_at) SELECT 'projects',id,remote_updated_at FROM projects WHERE remote_updated_at IS NOT NULL;
CREATE TRIGGER sync_projects_insert AFTER INSERT ON projects WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('projects',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'name',NEW.name,'description',NEW.description,'status',NEW.status,'color',NEW.color),(SELECT revision FROM native_sync_meta WHERE entity_table='projects' AND id=NEW.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='projects' AND id=NEW.id),NEW.remote_updated_at)); END;
CREATE TRIGGER sync_projects_update AFTER UPDATE ON projects WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('projects',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'name',NEW.name,'description',NEW.description,'status',NEW.status,'color',NEW.color),(SELECT revision FROM native_sync_meta WHERE entity_table='projects' AND id=NEW.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='projects' AND id=NEW.id),NEW.remote_updated_at)); END;
CREATE TRIGGER sync_projects_delete AFTER DELETE ON projects WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,base_revision,base_updated_at) VALUES('projects',OLD.id,'delete',(SELECT revision FROM native_sync_meta WHERE entity_table='projects' AND id=OLD.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='projects' AND id=OLD.id),OLD.remote_updated_at)); END;
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_updated_at) SELECT 'projects',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'name',NEW.name,'description',NEW.description,'status',NEW.status,'color',NEW.color),NEW.remote_updated_at FROM projects AS NEW WHERE sync_state!='imported';
INSERT INTO native_sync_meta(entity_table,id,remote_updated_at) SELECT 'tasks',id,remote_updated_at FROM tasks WHERE remote_updated_at IS NOT NULL;
CREATE TRIGGER sync_tasks_insert AFTER INSERT ON tasks WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('tasks',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'title',NEW.title,'description',NEW.description,'status',NEW.status,'priority',NEW.priority,'start_date',NEW.start_date,'due_date',NEW.due_date,'project_id',NEW.project_id),(SELECT revision FROM native_sync_meta WHERE entity_table='tasks' AND id=NEW.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='tasks' AND id=NEW.id),NEW.remote_updated_at)); END;
CREATE TRIGGER sync_tasks_update AFTER UPDATE ON tasks WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('tasks',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'title',NEW.title,'description',NEW.description,'status',NEW.status,'priority',NEW.priority,'start_date',NEW.start_date,'due_date',NEW.due_date,'project_id',NEW.project_id),(SELECT revision FROM native_sync_meta WHERE entity_table='tasks' AND id=NEW.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='tasks' AND id=NEW.id),NEW.remote_updated_at)); END;
CREATE TRIGGER sync_tasks_delete AFTER DELETE ON tasks WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,base_revision,base_updated_at) VALUES('tasks',OLD.id,'delete',(SELECT revision FROM native_sync_meta WHERE entity_table='tasks' AND id=OLD.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='tasks' AND id=OLD.id),OLD.remote_updated_at)); END;
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_updated_at) SELECT 'tasks',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'title',NEW.title,'description',NEW.description,'status',NEW.status,'priority',NEW.priority,'start_date',NEW.start_date,'due_date',NEW.due_date,'project_id',NEW.project_id),NEW.remote_updated_at FROM tasks AS NEW WHERE sync_state!='imported';
INSERT INTO native_sync_meta(entity_table,id,remote_updated_at) SELECT 'notes',id,remote_updated_at FROM notes WHERE remote_updated_at IS NOT NULL;
CREATE TRIGGER sync_notes_insert AFTER INSERT ON notes WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('notes',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'title',NEW.title,'content',NEW.content,'project_id',NEW.project_id),(SELECT revision FROM native_sync_meta WHERE entity_table='notes' AND id=NEW.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='notes' AND id=NEW.id),NEW.remote_updated_at)); END;
CREATE TRIGGER sync_notes_update AFTER UPDATE ON notes WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('notes',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'title',NEW.title,'content',NEW.content,'project_id',NEW.project_id),(SELECT revision FROM native_sync_meta WHERE entity_table='notes' AND id=NEW.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='notes' AND id=NEW.id),NEW.remote_updated_at)); END;
CREATE TRIGGER sync_notes_delete AFTER DELETE ON notes WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,base_revision,base_updated_at) VALUES('notes',OLD.id,'delete',(SELECT revision FROM native_sync_meta WHERE entity_table='notes' AND id=OLD.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='notes' AND id=OLD.id),OLD.remote_updated_at)); END;
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_updated_at) SELECT 'notes',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'title',NEW.title,'content',NEW.content,'project_id',NEW.project_id),NEW.remote_updated_at FROM notes AS NEW WHERE sync_state!='imported';
INSERT INTO native_sync_meta(entity_table,id,remote_updated_at) SELECT 'events',id,remote_updated_at FROM events WHERE remote_updated_at IS NOT NULL;
CREATE TRIGGER sync_events_insert AFTER INSERT ON events WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('events',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'title',NEW.title,'description',NEW.description,'start_at',NEW.start_at,'end_at',NEW.end_at,'project_id',NEW.project_id),(SELECT revision FROM native_sync_meta WHERE entity_table='events' AND id=NEW.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='events' AND id=NEW.id),NEW.remote_updated_at)); END;
CREATE TRIGGER sync_events_update AFTER UPDATE ON events WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('events',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'title',NEW.title,'description',NEW.description,'start_at',NEW.start_at,'end_at',NEW.end_at,'project_id',NEW.project_id),(SELECT revision FROM native_sync_meta WHERE entity_table='events' AND id=NEW.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='events' AND id=NEW.id),NEW.remote_updated_at)); END;
CREATE TRIGGER sync_events_delete AFTER DELETE ON events WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,base_revision,base_updated_at) VALUES('events',OLD.id,'delete',(SELECT revision FROM native_sync_meta WHERE entity_table='events' AND id=OLD.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='events' AND id=OLD.id),OLD.remote_updated_at)); END;
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_updated_at) SELECT 'events',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'title',NEW.title,'description',NEW.description,'start_at',NEW.start_at,'end_at',NEW.end_at,'project_id',NEW.project_id),NEW.remote_updated_at FROM events AS NEW WHERE sync_state!='imported';
INSERT INTO native_sync_meta(entity_table,id,remote_updated_at) SELECT 'library_items',id,remote_updated_at FROM library_items WHERE remote_updated_at IS NOT NULL;
CREATE TRIGGER sync_library_items_insert AFTER INSERT ON library_items WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('library_items',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'title',NEW.title,'description',NEW.description,'url',NEW.url,'type',NEW.type,'project_id',NEW.project_id),(SELECT revision FROM native_sync_meta WHERE entity_table='library_items' AND id=NEW.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='library_items' AND id=NEW.id),NEW.remote_updated_at)); END;
CREATE TRIGGER sync_library_items_update AFTER UPDATE ON library_items WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('library_items',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'title',NEW.title,'description',NEW.description,'url',NEW.url,'type',NEW.type,'project_id',NEW.project_id),(SELECT revision FROM native_sync_meta WHERE entity_table='library_items' AND id=NEW.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='library_items' AND id=NEW.id),NEW.remote_updated_at)); END;
CREATE TRIGGER sync_library_items_delete AFTER DELETE ON library_items WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,base_revision,base_updated_at) VALUES('library_items',OLD.id,'delete',(SELECT revision FROM native_sync_meta WHERE entity_table='library_items' AND id=OLD.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='library_items' AND id=OLD.id),OLD.remote_updated_at)); END;
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_updated_at) SELECT 'library_items',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'title',NEW.title,'description',NEW.description,'url',NEW.url,'type',NEW.type,'project_id',NEW.project_id),NEW.remote_updated_at FROM library_items AS NEW WHERE sync_state!='imported';
INSERT INTO native_sync_meta(entity_table,id,remote_updated_at) SELECT 'inbox_items',id,remote_updated_at FROM inbox_items WHERE remote_updated_at IS NOT NULL;
CREATE TRIGGER sync_inbox_items_insert AFTER INSERT ON inbox_items WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('inbox_items',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'content',NEW.content,'type',NEW.type),(SELECT revision FROM native_sync_meta WHERE entity_table='inbox_items' AND id=NEW.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='inbox_items' AND id=NEW.id),NEW.remote_updated_at)); END;
CREATE TRIGGER sync_inbox_items_update AFTER UPDATE ON inbox_items WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('inbox_items',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'content',NEW.content,'type',NEW.type),(SELECT revision FROM native_sync_meta WHERE entity_table='inbox_items' AND id=NEW.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='inbox_items' AND id=NEW.id),NEW.remote_updated_at)); END;
CREATE TRIGGER sync_inbox_items_delete AFTER DELETE ON inbox_items WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,base_revision,base_updated_at) VALUES('inbox_items',OLD.id,'delete',(SELECT revision FROM native_sync_meta WHERE entity_table='inbox_items' AND id=OLD.id),COALESCE((SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='inbox_items' AND id=OLD.id),OLD.remote_updated_at)); END;
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_updated_at) SELECT 'inbox_items',NEW.id,'put',json_object('id',NEW.id,'user_id',NEW.user_id,'created_at',NEW.created_at,'updated_at',NEW.updated_at,'content',NEW.content,'type',NEW.type),NEW.remote_updated_at FROM inbox_items AS NEW WHERE sync_state!='imported';
INSERT INTO native_sync_outbox(entity_table,id,action,base_updated_at) SELECT entity_table,id,'delete',remote_updated_at FROM tombstones;
CREATE TRIGGER sync_settings_update AFTER UPDATE ON workspace_settings WHEN (SELECT applying FROM native_sync_control)=0 BEGIN
INSERT INTO native_sync_outbox(entity_table,id,action,payload,base_revision,base_updated_at) VALUES('workspace_settings','settings','put',json_object('user_id',NEW.user_id,'workspace_name',NEW.workspace_name,'appearance',NEW.appearance,'display_name',NEW.display_name,'avatar_url',NEW.avatar_url,'updated_at',NEW.updated_at),(SELECT revision FROM native_sync_meta WHERE entity_table='workspace_settings' AND id='settings'),(SELECT remote_updated_at FROM native_sync_meta WHERE entity_table='workspace_settings' AND id='settings')); END;
INSERT INTO native_sync_outbox(entity_table,id,action,payload) SELECT 'workspace_settings','settings','put',json_object('user_id',NEW.user_id,'workspace_name',NEW.workspace_name,'appearance',NEW.appearance,'display_name',NEW.display_name,'avatar_url',NEW.avatar_url,'updated_at',NEW.updated_at) FROM workspace_settings AS NEW;
